#include "pch.h"
#include "CadSelectProcessor.h"
#include "Common.h"
#include "AgentTableSum.h"
#include <aced.h>
#include <adslib.h>
#include <dbents.h>
#include <zdbapserv.h>
#include <acdocman.h>
#include <fstream>
#include <sstream>
#include <thread>
#include <chrono>
#include <filesystem>

// Declarations of native CAD commands from rxentrypoint.cpp
extern void AiBomConvertCmd();
extern void AiTableRecognizeCmd();

namespace NS_CadSelect
{
    void CadSelectProcessor::SelectionTaskFunc(void* pData)
    {
        SelectionTaskData* pTask = static_cast<SelectionTaskData*>(pData);
        if (!pTask || !pTask->pPromise) return;

        SelectResult result;
        result.success = false;

        bool isBomMode = (pTask->convertMode == 1);
        acutPrintf(L"\n[AI Convert] Triggering native CAD command (%s)...", isBomMode ? L"AI_BOM_Convert" : L"AI_TABLE_RECOGNIZE");

        // 1. Directly execute native CAD command (handles viewport selection, OCR & Dify workflow natively)
        if (isBomMode)
        {
            AiBomConvertCmd();
        }
        else
        {
            AiTableRecognizeCmd();
        }

        // 2. Locate the output JSON file generated by the native CAD command
        std::wstring targetDir = isBomMode ? 
            L"C:\\Users\\zwsoft\\Desktop\\transform\\BOM_testdata\\dify_results\\" : 
            L"C:\\Users\\zwsoft\\Desktop\\transform\\testdata\\dify_results\\";

        ZcDbDatabase* pDb = zcdbHostApplicationServices()->workingDatabase();
        ZcString dwgPath;
        if (pDb)
        {
            const ZTCHAR* pDwgName = nullptr;
            pDb->getFilename(pDwgName);
            dwgPath = pDwgName ? pDwgName : L"";
        }
        ZcString shortFileName = GetShortFileName(dwgPath);
        if (shortFileName.isEmpty())
        {
            shortFileName = isBomMode ? L"AiBomConvert" : L"AiTableRecognize";
        }

        std::wstring resultJsonPath = targetDir + shortFileName.kwszPtr() + L".json";

        // Read the native command's JSON output file
        std::ifstream ifs(resultJsonPath, std::ios::binary);
        std::string resultJsonStr = "";
        if (ifs.is_open())
        {
            std::stringstream ssBuf;
            ssBuf << ifs.rdbuf();
            resultJsonStr = ssBuf.str();
            ifs.close();
        }

        if (!resultJsonStr.empty())
        {
            try {
                nlohmann::json respJson = nlohmann::json::parse(resultJsonStr);
                if (respJson.contains("data") && respJson["data"].contains("outputs"))
                {
                    result.extractedFields = respJson["data"]["outputs"];
                }
                else
                {
                    result.extractedFields = respJson;
                }
                result.success = true;
            } catch (std::exception& e) {
                result.success = false;
                result.errorMsg = std::string("Failed to parse native Dify JSON output: ") + e.what();
            }
        }
        else
        {
            result.success = false;
            result.errorMsg = "Native CAD command output file not found or empty: " + wstring2string(resultJsonPath);
        }

        pTask->pPromise->set_value(result);
    }

    SelectResult CadSelectProcessor::ExecuteRealSelection(int convertMode)
    {
        std::promise<SelectResult> selPromise;
        std::future<SelectResult> selFuture = selPromise.get_future();

        SelectionTaskData taskData;
        taskData.convertMode = convertMode;
        taskData.pPromise = &selPromise;

        // Execute in Application Context (CAD Main Thread) to avoid UI deadlock
        acDocManager->executeInApplicationContext(SelectionTaskFunc, &taskData);

        // Wait for main thread UI interaction to complete (timeout: 120s)
        std::future_status status = selFuture.wait_for(std::chrono::seconds(120));
        if (status == std::future_status::ready)
        {
            return selFuture.get();
        }
        else
        {
            SelectResult errRes;
            errRes.success = false;
            errRes.errorMsg = "Selection timed out waiting for CAD UI user input";
            return errRes;
        }
    }
}